version: '3'
services:
  crime_everyday:
    container_name: crime_everyday
    build:
      context: .
      dockerfile: Dockerfile.crime_everyday
    command: python -u crime_everyday.py
    environment:
      - TZ=Asia/Almaty
    restart: always