FROM python:3.10

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && apt-get install -y libpq-dev

RUN pip install --no-cache-dir -r requirements.txt

COPY road_traffic.py .

CMD [ "python", "-u", "road_traffic.py" ]
